import seedDrivers from '../data/drivers.js'
import seedLoads from '../data/loads.js'
import mapLocations from '../data/mapLocations.js'
import { calculateRoute } from '../services/routingService.js'
import seedCarriers from '../data/carriers.js'

const pointAlong = (route, progress) => { const i = Math.min(route.length - 2, Math.floor(progress * (route.length - 1))); const t = progress * (route.length - 1) - i; return [route[i][0] + (route[i + 1][0] - route[i][0]) * t, route[i][1] + (route[i + 1][1] - route[i][1]) * t] }

export async function createDevPreset(name, { gameTime, currentLoads = seedLoads, currentDrivers = seedDrivers } = {}) {
  const load = { ...(currentLoads.find((item) => item.id === 'DOC001') || seedLoads[0]) }; const driver = { ...(currentDrivers.find((item) => item.id === 'marcus') || seedDrivers[0]) }
  const pickup = mapLocations.find((item) => item.id === load.pickupLocationId); const delivery = mapLocations.find((item) => item.id === load.deliveryLocationId); const now = (gameTime?.gameDayIndex ?? 0) * 1440 + (gameTime?.totalMinutesOfDay ?? 420)
  const yard = mapLocations.find((item) => item.id === 'metroline-yard')
  const base = { selectedMarket: 'new-york', gameTime: gameTime || { gameDayIndex: 0, totalMinutesOfDay: 420 }, loads: [load], drivers: [driver], carriers: seedCarriers.map((carrier) => ({ ...carrier, status: 'active' })), runtimePositions: yard ? { marcus: { longitude: yard.longitude, latitude: yard.latitude } } : {}, runtimeProgress: null, stage: 'game' }
  if (name === 'no-client') return { ...base, carriers: seedCarriers.map((carrier) => ({ ...carrier, status: 'prospect' })), drivers: [], runtimePositions: {}, loads: [seedLoads[0]] }
  if (name === 'metroline-active') { driver.status = 'available'; return { ...base, drivers: [driver], loads: [seedLoads[0]] } }
  if (name === 'driver-fit') return base
  load.status = 'accepted'; load.tripStatus = 'assigned'; load.assignedDriverId = 'marcus'; load.candidateDriverId = null; load.carrierId = driver.carrierId ?? null; driver.status = 'unavailable'
  const at = (point) => ({ ...base, loads: [load], drivers: [driver], runtimePositions: { marcus: { longitude: point[0], latitude: point[1] } } })
  if (name === 'accepted') return { ...base, loads: [load], drivers: [driver] }
  if (name === 'waiting-at-pickup' || name === 'loading') { load.tripStatus = name === 'loading' ? 'loading-at-pickup' : 'waiting-at-pickup'; load.pickupArrivalGameMinute = now; if (name === 'loading') load.loadingStartGameMinute = now - 2; return at([pickup.longitude, pickup.latitude]) }
  if (name === 'loaded') { load.tripStatus = 'loaded'; return at([pickup.longitude, pickup.latitude]) }
  if (name === 'load-complete') { load.tripStatus='completed'; load.status='completed'; load.assignedDriverId=null; load.completedDriverId='marcus'; driver.status='available'; driver.assignedLoadId=null; load.pod={status:'complete',receivedGameMinute:now,viewedGameMinute:now,signedBy:'Jordan Rivera',piecesExpected:12,piecesReceived:12,damage:'None',verification:{signature:true,pieceCount:true,damage:true,deliveryInfo:true},verified:true,verifiedGameMinute:now,approved:true,approvedGameMinute:now}; return {...at([delivery.longitude,delivery.latitude]), loads:[load], drivers:[driver]} }
  if (name === 'pod-ready' || name === 'pod-verified') { Object.keys(load).forEach((key) => { if (key.includes('Route') || key.includes('route') || key.includes('Miles') || key.includes('DriveTime') || key.includes('GameMinute') || key.includes('planningStatus') || key === 'completedDriverId') load[key] = null }); load.tripStatus = 'awaiting-pod'; load.status = 'accepted'; const complete = name === 'pod-verified'; load.pod = { status: 'complete', receivedGameMinute: now, viewedGameMinute: complete ? now : null, signedBy: 'Jordan Rivera', piecesExpected: 12, piecesReceived: 12, damage: 'None', verification: { signature: complete, pieceCount: complete, damage: complete, deliveryInfo: complete }, verified: complete, verifiedGameMinute: complete ? now : null }; return at([delivery.longitude, delivery.latitude]) }
  if (name === 'waiting-at-delivery' || name === 'unloading') { load.tripStatus = name === 'unloading' ? 'unloading-delivery' : 'at-delivery'; if (name === 'unloading') load.deliveryUnloadStartGameMinute = now - 2; return at([delivery.longitude, delivery.latitude]) }
  if (['ready-for-pickup-dispatch', 'en-route-pickup'].includes(name)) { const route = load.plannedDeadheadRouteGeometry?.length ? { routeShape: load.plannedDeadheadRouteGeometry, distanceMiles: load.plannedDeadheadMiles, durationMinutes: load.plannedDeadheadDriveTimeMinutes } : await calculateRoute(yard, pickup); load.planningStatus = 'route-ready'; load.plannedDeadheadRouteGeometry = route.routeShape; load.plannedDeadheadMiles = route.distanceMiles; load.plannedDeadheadDriveTimeMinutes = route.durationMinutes; load.selectedDeadheadRouteId = 'recommended'; if (name === 'en-route-pickup') { load.tripStatus = 'en-route-pickup'; const progress = .45; load.departureGameMinute = now - route.durationMinutes * progress; return { ...at(pointAlong(route.routeShape, progress)), runtimeProgress: progress } } return { ...base, loads: [load], drivers: [driver] } }
  if (['ready-for-delivery-dispatch', 'en-route-delivery'].includes(name)) { load.tripStatus = 'loaded'; const route = load.plannedLoadedRouteGeometry?.length ? { routeShape: load.plannedLoadedRouteGeometry, distanceMiles: load.plannedLoadedMiles, durationMinutes: load.plannedLoadedDriveTimeMinutes } : await calculateRoute(pickup, delivery); load.deliveryPlanningStatus = 'route-ready'; load.plannedLoadedRouteGeometry = route.routeShape; load.plannedLoadedMiles = route.distanceMiles; load.plannedLoadedDriveTimeMinutes = route.durationMinutes; load.selectedLoadedRouteId = 'recommended'; if (name === 'en-route-delivery') { load.tripStatus = 'en-route-delivery'; const progress = .45; load.deliveryDepartureGameMinute = now - route.durationMinutes * progress; return { ...at(pointAlong(route.routeShape, progress)), runtimeProgress: progress } } return at([pickup.longitude, pickup.latitude]) }
  return { ...base, loads: [load], drivers: [driver] }
}
